spring.application.name=gestion_atelier

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_atelier
spring.datasource.username=postgres
spring.datasource.password=500227
#   Le Traducteur entre java et postgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
# Ila lqa frq f code java w sql mamntabqch kiblocke kolchi (erreur de demarrage)
spring.jpa.hibernate.ddl-auto=validate
# Bach ntestiw w ndeboguiw
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080